# 应用服务 WEB 访问端口
server:
  port: 8081

# 应用名称
spring:
  application:
    name: base
# 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
# 数据库连接地址
    url: jdbc:mysql://localhost:3306/dblg?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false
# 数据库用户名&密码：
    username: root
    password: rootAuthentication
  security:
    user:
      password: admin
      name: admin
